hugoblox:
  schema: "2.0"
  identity:
    name: Leon Küstermann
    type: person
    tagline: Postdoctoral researcher | University of Zurich
    description: ""
  theme:
    mode: light
    pack: minimal
    colors:
      primary: "#454d3e"
      secondary: "#ffffff"
      neutral: ""
    colors_light:
      primary: ""
  typography:
    font: serif
    size: md
  layout:
    radius: none
    spacing: compact
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo:
    title: Leon Küstermann
  verification:
    google: e4MUCTPjxalhkNNoAiY6FJK_91ERSR07sr_DRFJXYzA
