hugoblox:
  schema: "2.0"
  identity:
    name: Leon Küstermann
    type: person
    tagline: Postdoctoral researcher | University of Zurich
    description: ""
  theme:
    mode: system
    pack: marine
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
